/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data.mahasiswa;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Data extends javax.swing.JFrame {
    
    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        viewData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngJenKel = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinput = new javax.swing.JTable();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        cbxAktif = new javax.swing.JCheckBox();
        cbxTidakAktif = new javax.swing.JCheckBox();
        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbxAgama = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxProdi = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(595, 595));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 60));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA MAHASISWA");
        jLabel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 43));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel3.setForeground(new java.awt.Color(67, 41, 31));

        txtNim.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        txtNama.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nama");

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nomor hp");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agama");

        txtNohp.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jenis kelamin");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Status");

        btnHapus.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/apus (1).jpg"))); // NOI18N
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/update.jpg"))); // NOI18N
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        tblinput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblinput.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Email", "No hp", "Jenis kelamin", "Agama", "Status", "Prodi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblinput.setGridColor(new java.awt.Color(204, 204, 204));
        tblinput.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblinput.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblinput.setShowGrid(true);
        tblinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblinput);

        rdLaki.setBackground(new java.awt.Color(0, 0, 0));
        btngJenKel.add(rdLaki);
        rdLaki.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        rdLaki.setForeground(new java.awt.Color(255, 255, 255));
        rdLaki.setText("Laki-laki");

        rdPerempuan.setBackground(new java.awt.Color(0, 0, 0));
        btngJenKel.add(rdPerempuan);
        rdPerempuan.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        rdPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rdPerempuan.setText("Perempuan");

        cbxAktif.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(cbxAktif);
        cbxAktif.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbxAktif.setForeground(new java.awt.Color(255, 255, 255));
        cbxAktif.setText("Aktif");

        cbxTidakAktif.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(cbxTidakAktif);
        cbxTidakAktif.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbxTidakAktif.setForeground(new java.awt.Color(255, 255, 255));
        cbxTidakAktif.setText("Tidak Aktif");
        cbxTidakAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTidakAktifActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/cari (1).jpg"))); // NOI18N
        btnCari.setToolTipText("");
        btnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/tambah.jpg"))); // NOI18N
        btnTambah.setToolTipText("");
        btnTambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambah.setMaximumSize(new java.awt.Dimension(40, 24));
        btnTambah.setMinimumSize(new java.awt.Dimension(40, 24));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icons/reset (1).jpg"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        cbxAgama.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbxAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Atheis" }));
        cbxAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgamaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prodi");

        cbxProdi.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cbxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Atheis" }));
        cbxProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(cbxAktif)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbxTidakAktif))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(rdLaki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdPerempuan)))))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxAktif)
                    .addComponent(cbxTidakAktif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdLaki)
                    .addComponent(rdPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 480));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void clear(){
        txtNama.setText("");
        txtNim.setText("");
        txtNohp.setText("");
        txtEmail.setText("");
        cbxProdi.setSelectedItem("Pilih");
        btngJenKel.clearSelection();
        buttonGroup1.clearSelection();
    }
    
    private boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
    
    private void cariKe2(Connection con, String nim, String nama, String noHp, String email, String agama, String jenisKelamin, String status){
        Statement st;
        try {
            st = con.createStatement();
            
            if(nama.isEmpty() || nama.isBlank()){
                resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+nim+"' OR Email='"+email+"' OR NoHp='"+noHp+"' OR Agama='"+agama+"' OR JenisKelamin='"+jenisKelamin+"' OR Status='"+status+"'");
                while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("Nim"),
                    resultSet.getString("Nama"),
                    resultSet.getString("Email"),
                    resultSet.getString("NoHp"),
                    resultSet.getString("JenisKelamin"),
                    resultSet.getString("Agama"),
                    resultSet.getString("Status")
                };
                    tableModel.addRow(data);
                }
            }else{
                resultSet = st.executeQuery("SELECT * FROM data WHERE Nama Like '%"+nama+"%'");
                while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("Nim"),
                    resultSet.getString("Nama"),
                    resultSet.getString("Email"),
                    resultSet.getString("NoHp"),
                    resultSet.getString("JenisKelamin"),
                    resultSet.getString("Agama"),
                    resultSet.getString("Status")
                };
                    tableModel.addRow(data);
                }
            }
            
            con.close();
            clear();
        } catch (SQLException ex) {
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cari(String nim, String nama, String noHp, String email, String agama, String jenisKelamin, String status){
        try{
            //koneksi ke database
            Connection con = connectionToDB.ConnectDB();
            
            //Model tabel
            Object[] columnTitle = {"Nim", "Nama", "Email", "No hp", "Jenis kelamin", "Agama", "Status"};
            tableModel = new DefaultTableModel(null, columnTitle);
            tblinput.setModel(tableModel);
            tableModel.getDataVector().removeAllElements();
            
            //Buat statement
            Statement st = con.createStatement();
            if(nim != null && (nama.isEmpty() || nama.isBlank()) && (email.isEmpty() || email.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && agama.equals("Pilih") && jenisKelamin == null && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if(nama != null && (nim.isEmpty() || nim.isBlank()) && (email.isEmpty() || email.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && agama.equals("Pilih") && jenisKelamin == null && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if(email != null && (nim.isEmpty() || nim.isBlank()) && (nama.isEmpty() || nama.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && agama.equals("Pilih") && jenisKelamin == null && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if(noHp != null && (nim.isEmpty() || nim.isBlank()) && (nama.isEmpty() || nama.isBlank()) && (email.isEmpty() || email.isBlank()) && agama.equals("Pilih") && jenisKelamin == null && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if(true != agama.equals("Pilih") &&(nim.isEmpty() || nim.isBlank()) && (nama.isEmpty() || nama.isBlank()) && (email.isEmpty() || email.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && jenisKelamin == null && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if( jenisKelamin != null && (nim.isEmpty() || nim.isBlank()) && (nama.isEmpty() || nama.isBlank()) && (email.isEmpty() || email.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && agama.equals("Pilih") && status == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else if( status != null && (nim.isEmpty() || nim.isBlank()) && (nama.isEmpty() || nama.isBlank()) && (email.isEmpty() || email.isBlank()) && (noHp.isEmpty() || noHp.isBlank()) && agama.equals("Pilih") && jenisKelamin == null){
                cariKe2(con, nim, nama, noHp, email, agama, jenisKelamin, status);
            }else{
                if(nim != null){
                    resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+nim+"' AND Nama='"+nama+"' AND Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"'");
                    while(resultSet.next()){
                    Object[] data = {
                        resultSet.getString("Nim"),
                        resultSet.getString("Nama"),
                        resultSet.getString("Email"),
                        resultSet.getString("NoHp"),
                        resultSet.getString("JenisKelamin"),
                        resultSet.getString("Agama"),
                        resultSet.getString("Status")
                    };
                        tableModel.addRow(data);
                    }
                }else{
                   resultSet = st.executeQuery("SELECT * FROM data WHERE (Nama='"+nama+"' AND Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"') OR (Nama='"+nama+"' AND Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"') OR (Nama='"+nama+"' AND Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"') OR (Nama='"+nama+"' AND Email='"+email+"' AND NoHp='"+noHp+"') OR (Nama='"+nama+"' AND Email='"+email+"') OR (Nama='"+nama+"' AND NoHp='"+noHp+"') OR (Nama='"+nama+"' AND Agama='"+agama+"') OR (Nama='"+nama+"' AND Status='"+status+"') OR (Nama='"+nama+"' AND JenisKelamin='"+jenisKelamin+"')" +
                    " OR (Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"') OR (Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"') OR (Email='"+email+"' AND NoHp='"+noHp+"' AND Agama='"+agama+"') OR (Email='"+email+"' AND NoHp='"+noHp+"') OR (Email='"+email+"' AND Agama='"+agama+"') OR (Email='"+email+"' AND JenisKelamin='"+jenisKelamin+"') OR (Email='"+email+"' AND Status='"+status+"')" +
                    " OR (NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"') OR (NoHp='"+noHp+"' AND Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"') OR (NoHp='"+noHp+"' AND Agama='"+agama+"') OR (NoHp='"+noHp+"' AND JenisKelamin='"+jenisKelamin+"') OR (NoHp='"+noHp+"' AND Status='"+status+"')" +
                    " OR (Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"') OR (Agama='"+agama+"' AND JenisKelamin='"+jenisKelamin+"')  OR (Agama='"+agama+"' AND Status='"+status+"')" +
                    " OR (JenisKelamin='"+jenisKelamin+"' AND Status='"+status+"')");
            
                    while(resultSet.next()){
                    Object[] data = {
                        resultSet.getString("Nim"),
                        resultSet.getString("Nama"),
                        resultSet.getString("Email"),
                        resultSet.getString("NoHp"),
                        resultSet.getString("JenisKelamin"),
                        resultSet.getString("Agama"),
                        resultSet.getString("Status")
                    };
                    tableModel.addRow(data);
                    } 
                }
            }
            
            clear();
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private final String regex2 = "^[a-zA-Z+\\s.]*$";
    private final String regex = "\\d+";
    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    private void viewData(){
        try{
            //koneksi ke database
            Connection con = connectionToDB.ConnectDB();
            
            //Model tabel
            Object[] columnTitle = {"Nim", "Nama", "Email", "No hp", "Jenis kelamin", "Agama", "Status"};
            tableModel = new DefaultTableModel(null, columnTitle);
            tblinput.setModel(tableModel);
            tableModel.getDataVector().removeAllElements();
            
            //Buat statement
            Statement st = con.createStatement();
            resultSet = st.executeQuery("SELECT * FROM data");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("Nim"),
                    resultSet.getString("Nama"),
                    resultSet.getString("Email"),
                    resultSet.getString("NoHp"),
                    resultSet.getString("JenisKelamin"),
                    resultSet.getString("Agama"),
                    resultSet.getString("Status")
                };
                tableModel.addRow(data);
            }
            con.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void cbxProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProdiActionPerformed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
            // TODO add your handling code here:
            final String nama = txtNama.getText();
            final String nim = txtNim.getText();
            final String email = txtEmail.getText();
            final String noHp = txtNohp.getText();
            final String agama = cbxProdi.getSelectedItem().toString();
                      
            if((nama.isBlank() || nama.isEmpty()) || (nim.isBlank() || nim.isEmpty()) || (email.isBlank() || email.isEmpty()) || (noHp.isBlank() || noHp.isEmpty()) || agama.equals("Pilih") || (rdLaki.isSelected() == false && rdPerempuan.isSelected() == false) || (cbxAktif.isSelected() == false && cbxTidakAktif.isSelected() == false)){
                JOptionPane.showMessageDialog(null, "Semua data wajib diisi", "Invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nim.length() < 9 || nim.length() > 9){
                txtNim.setText("");
                JOptionPane.showMessageDialog(null, "nim harus 9 angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nim.matches(regex) != true){
                txtNim.setText("");
                JOptionPane.showMessageDialog(null, "nim harus angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nama.length() < 3){
                txtNama.setText("");
                JOptionPane.showMessageDialog(null, "nama harus lebih dari 3 huruf", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nama.matches(regex2) != true){
                txtNama.setText("");
                JOptionPane.showMessageDialog(null, "Nama harus huruf", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(isValidEmailAddress(email) == false){
                txtEmail.setText("");
                JOptionPane.showMessageDialog(null, "email tidak valid", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(noHp.length() < 11 || noHp.length() > 13 || (noHp.indexOf("0") != 0 && noHp.indexOf("8") != 1)){
                txtNohp.setText("");
                JOptionPane.showMessageDialog(null, "no hp tidak valid ", "invalid", JOptionPane.ERROR_MESSAGE);
            }
            else if(noHp.matches(regex) != true){
                txtNohp.setText("");
                JOptionPane.showMessageDialog(null, "no hp harus angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }
            else{
                try (Connection con = connectionToDB.ConnectDB()) {
                  
                    
                    Statement st = con.createStatement();
                    resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+nim+"'");
                    Boolean findUser = false;
                    while(resultSet.next()){
                        findUser = true;
                    }
                    
                    if(findUser){
                        JOptionPane.showMessageDialog(null, "Data sudah ada", "Invalid", JOptionPane.ERROR_MESSAGE);
                        con.close();
                        return;
                    }
                    
                    final String jenisKelamin = rdLaki.isSelected() ? rdLaki.getText() : rdPerempuan.getText();
                    final String status = cbxAktif.isSelected() ? cbxAktif.getText() : cbxTidakAktif.getText();
                    String sql = "INSERT INTO `data`(`Nim`, `Nama`, `Email`, `NoHp`, `Agama`, `JenisKelamin`, `Status`) VALUES ("
                            + "'"+nim+"'"
                            + ",'"+nama+"'"
                            + ",'"+email+"'"
                            + ",'"+noHp+"'"
                            + ",'"+agama+"'"
                            + ",'"+jenisKelamin+"'"
                            + ",'"+status+"')";
                    PreparedStatement preparedStmt = con.prepareStatement(sql);
                    preparedStmt.execute();
                    clear();
                    viewData();
                    con.close();
                    JOptionPane.showMessageDialog(null, "Berhasil memasukkan data", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void cbxTidakAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTidakAktifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTidakAktifActionPerformed

    private void tblinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinputMouseClicked
        //ambil data dari table
        String getData = (String) tblinput.getValueAt(tblinput.getSelectedRow() , 0);
        
        try{
            //koneksi ke database
            Connection con = connectionToDB.ConnectDB();
            
            //Buat statement
            Statement st = con.createStatement();
            resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+getData+"'");
            while(resultSet.next()){
                txtNama.setText(resultSet.getString("Nama"));
                txtNim.setText(resultSet.getString("Nim"));
                txtNohp.setText(resultSet.getString("NoHp"));
                txtEmail.setText(resultSet.getString("Email"));
                cbxProdi.setSelectedItem(resultSet.getString("Agama"));
                if(resultSet.getString("JenisKelamin").equals("Laki-laki")){
                    rdLaki.setSelected(true);
                }else{
                    rdPerempuan.setSelected(true);
                }
                
                if(resultSet.getString("Status").equals("Aktif")){
                    cbxAktif.setSelected(true);
                }else{
                    cbxTidakAktif.setSelected(true); 
                }
            }
        }catch(SQLException e){
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tblinputMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        try{
            Connection con = connectionToDB.ConnectDB();
            Statement st = con.createStatement();
            resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+txtNim.getText()+"'");
            Boolean findUser = false;
            while(resultSet.next()){
                findUser = true;
            }
            
            if(findUser == false){
                JOptionPane.showMessageDialog(null, "Data tidak ada", "Invalid", JOptionPane.ERROR_MESSAGE);
                con.close();
                return;
            }
            
            if(JOptionPane.showConfirmDialog(null, "Yakin?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String delete = "DELETE FROM data WHERE Nim='"+txtNim.getText()+"'";
                PreparedStatement prs = con.prepareStatement(delete);
                prs.execute();
            }
            
            viewData();
            clear();
        }catch(SQLException e){
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        // TODO add your handling code here:
//        try{
            final String nama = txtNama.getText();
            final String nim = txtNim.getText();
            final String email = txtEmail.getText();
            final String noHp = txtNohp.getText();
            final String agama = cbxProdi.getSelectedItem().toString();
            final String jenisKelamin = rdLaki.isSelected()? "Laki-laki" : rdPerempuan.isSelected()? "Perempuan" : null;
            final String statusMhs = cbxAktif.isSelected()? "Aktif" : cbxTidakAktif.isSelected()? "Tidak Aktif" : null;
            
            cari(nim, nama, noHp, email, agama, jenisKelamin, statusMhs);
            //koneksi ke database
//            Connection con = connectionToDB.ConnectDB();
//            
//            //Model tabel
//            Object[] columnTitle = {"Nim", "Nama", "Email", "No hp", "Jenis kelamin", "Agama", "Status"};
//            tableModel = new DefaultTableModel(null, columnTitle);
//            tblinput.setModel(tableModel);
//            tableModel.getDataVector().removeAllElements();
//            
//            //Buat statement
//            Statement st = con.createStatement();
//            
//            if(nama.isEmpty() || nama.isBlank()){
//                resultSet = st.executeQuery("SELECT * FROM data WHERE (Nim='"+nim+"') OR (Email='"+email+"') OR (NoHp='"+noHp+"') OR (Agama='"+agama+"') OR (JenisKelamin='"+jenisKelamin+"') OR (Status='"+statusMhs+"')");
//                while(resultSet.next()){
//                Object[] data = {
//                    resultSet.getString("Nim"),
//                    resultSet.getString("Nama"),
//                    resultSet.getString("Email"),
//                    resultSet.getString("NoHp"),
//                    resultSet.getString("JenisKelamin"),
//                    resultSet.getString("Agama"),
//                    resultSet.getString("Status")
//                };
//                tableModel.addRow(data);
//                }
//            }else{
//                resultSet = st.executeQuery("SELECT * FROM data WHERE Nama LIKE '%"+nama+"%' OR Nim='"+nim+"' OR Email='"+email+"' OR NoHp='"+noHp+"' OR Agama='"+agama+"' OR JenisKelamin='"+jenisKelamin+"' OR Status='"+statusMhs+"'");
//                while(resultSet.next()){
//                Object[] data = {
//                    resultSet.getString("Nim"),
//                    resultSet.getString("Nama"),
//                    resultSet.getString("Email"),
//                    resultSet.getString("NoHp"),
//                    resultSet.getString("JenisKelamin"),
//                    resultSet.getString("Agama"),
//                    resultSet.getString("Status")
//                };
//                tableModel.addRow(data);
//                }
//            }
//            clear();
//            con.close();
//        }catch(SQLException e){
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_btnCariMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        try{
            final String nama = txtNama.getText();
            final String nim = txtNim.getText();
            final String email = txtEmail.getText();
            final String noHp = txtNohp.getText();
            final String agama = cbxProdi.getSelectedItem().toString();
            final String jenisKelamin = rdLaki.isSelected()? "Laki-laki" : rdPerempuan.isSelected()? "Perempuan" : null;
            final String statusMhs = cbxAktif.isSelected()? "Aktif" : cbxTidakAktif.isSelected()? "Tidak Aktif" : null;
            //koneksi ke database
            Connection con = connectionToDB.ConnectDB();
            
            Statement st = con.createStatement();
            resultSet = st.executeQuery("SELECT * FROM data WHERE Nim='"+txtNim.getText()+"'");
            Boolean findUser = false;
            while(resultSet.next()){
                findUser = true;
            }
            
            if(findUser == false){
                JOptionPane.showMessageDialog(null, "Data tidak ada", "Invalid", JOptionPane.ERROR_MESSAGE);
                con.close();
                clear();
                return;
            }
           
            if((nama.isBlank() || nama.isEmpty()) || (nim.isBlank() || nim.isEmpty()) || (email.isBlank() || email.isEmpty()) || (noHp.isBlank() || noHp.isEmpty()) || agama.equals("Pilih") || (jenisKelamin.isEmpty() || jenisKelamin.isBlank()) || (statusMhs.isEmpty() && statusMhs.isBlank())){
                JOptionPane.showMessageDialog(null, "Semua data wajib diisi", "Invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nim.length() < 9 || nim.length() > 9){
                txtNim.setText("");
                JOptionPane.showMessageDialog(null, "nim harus 9 angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nim.matches(regex) != true){
                txtNim.setText("");
                JOptionPane.showMessageDialog(null, "nim harus angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nama.length() < 3){
                txtNama.setText("");
                JOptionPane.showMessageDialog(null, "nama harus lebih dari 3 huruf", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(nama.matches(regex2) != true){
                txtNama.setText("");
                JOptionPane.showMessageDialog(null, "Nama harus huruf", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(isValidEmailAddress(email) == false){
                txtEmail.setText("");
                JOptionPane.showMessageDialog(null, "email tidak valid", "invalid", JOptionPane.ERROR_MESSAGE);
            }else if(noHp.length() < 11 || noHp.length() > 13 || (noHp.indexOf("0") != 0 && noHp.indexOf("8") != 1)){
                txtNohp.setText("");
                JOptionPane.showMessageDialog(null, "no hp tidak valid ", "invalid", JOptionPane.ERROR_MESSAGE);
            }
            else if(noHp.matches(regex) != true){
                txtNohp.setText("");
                JOptionPane.showMessageDialog(null, "no hp harus angka", "invalid", JOptionPane.ERROR_MESSAGE);
            }else{
                String sql = "UPDATE data SET Nim='"+txtNim.getText()+"', Nama='"+txtNama.getText()+"', Email='"+txtEmail.getText()+"',NoHp='"+txtNohp.getText()+"', Agama='"+cbxProdi.getSelectedItem().toString()+"', JenisKelamin='"+jenisKelamin+"', Status='"+statusMhs+"' WHERE Nim='"+ txtNim.getText() +"'";
                PreparedStatement preparedStmt = con.prepareStatement(sql);
                preparedStmt.execute();
                JOptionPane.showMessageDialog(null, "Berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);
                con.close();
            }
            viewData();
            clear();
        }catch(SQLException e){
             Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cbxAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAgamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup btngJenKel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxAgama;
    private javax.swing.JCheckBox cbxAktif;
    private javax.swing.JComboBox<String> cbxProdi;
    private javax.swing.JCheckBox cbxTidakAktif;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tblinput;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtNohp;
    // End of variables declaration//GEN-END:variables
}
